image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - mkaufman.HTMLHint@0.6.0:TdNYbCmjW8N3yiaPW4/adg==
    - eventyret.bootstrap-4-cdn-snippet@1.6.0:AtNd6GnbCYVpmUkOaFXs3A==
    - kevinglasson.cornflakes-linter@0.4.0:Sgfmpf9YWoF5/BDJu2xn0w==
    - formulahendry.auto-close-tag@0.5.9:+RYHu1HN3BGIwbss/7NjBA==
    - esbenp.prettier-vscode@5.7.1:GDba64T6G+TUi1qmc6BE3A==
    - ms-python.python@2020.9.112786:xkt5+oIkGOB7bQ9XuIOLRA==